

spring:
  datasource:
    profile: r
    username: root
    url: jdbc:mariadb://localhost:3306/dev?createDatabaseIfNotExist=true
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
      ddl-auto: update


server:
  port: 1111

  spring:
    h2:
      console:
        enabled: 'true'