#spring:
#  profiles:
#    active: dev
#
#server:
#  port: 1234
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#        exclude: "beans"



spring:
  main:
    allow-circular-references: 'true'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB106Dialect
        use_sql_comments: 'true'
        show_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      enabled: 'true'
      max-request-size: 10MB
      file-size-threshold: 2MB
  datasource:
    password: root
    username: root
    url: jdbc:mariadb://127.0.0.1:3306/Store?createDatabaseIfNotExist=true
welcome:
  message: Welcome to our welcome page !!
server:
  port: '8080'
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
key: '12345'







